#!/usr/bin/env python3
"""Build a Plotly Cloud upload bundle from the installable package.

Plotly Cloud installs your *dependencies*, not your app: whatever you upload is
what lands on ``sys.path``. A ``src``-layout package therefore breaks there —
``from earthquake_dashboard.data_loader import ...`` has no
``earthquake_dashboard`` package to resolve against unless the project is pip
installed, which the platform does not do. So the bundle is the package's
*contents* hoisted to the root, with those imports rewritten to plain modules.

Dependencies ship as ``requirements.txt`` rather than the project's own
``pyproject.toml``: that file's ``[build-system]`` section points hatchling at
``src/earthquake_dashboard``, a path the flattened bundle does not have.

The entrypoint is renamed on the way in. Plotly Cloud fixes an app's entrypoint
module at its *first* publish and refuses to change it afterwards, and the live
app was first published from a copy whose entrypoint was ``app2.py``. Uploading
an ``app.py`` to it makes gunicorn fail to boot with FileNotFoundError on
``app2.py``, so that name is the default here. A brand-new app can take
``--entrypoint app.py``, which is what Cloud auto-detects.

Usage:
    pixi run bundle                          # dist/earthquake-dashboard-plotly/ + .zip
    pixi run bundle --entrypoint app.py      # for a new app, not the live one
    pixi run bundle --no-zip                 # directory only, to drag into the UI
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tomllib
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PACKAGE = REPO / "src" / "earthquake_dashboard"
PYPROJECT = REPO / "pyproject.toml"

# The package module that defines the Dash app, and the name it must take in the
# bundle. They differ because the live app's entrypoint is frozen as `app2` — see
# the module docstring.
APP_MODULE = "app.py"
DEFAULT_ENTRYPOINT = "app2.py"

# 80 MiB in the web UI, 200 MiB from the CLI or dev tools. Check against the
# tighter of the two, since the UI is the path this bundle exists to serve.
UI_SIZE_LIMIT = 80 * 1024 * 1024

# Files that only make sense inside an installed package.
SKIP_NAMES = {"__init__.py"}
SKIP_DIRS = {"__pycache__"}

IMPORT_RE = re.compile(r"^from earthquake_dashboard\.(\w+) import ", re.MULTILINE)


def collect() -> list[Path]:
    """Package files to ship, as paths relative to the package root."""
    files = []
    for path in sorted(PACKAGE.rglob("*")):
        if not path.is_file():
            continue
        if path.name in SKIP_NAMES or path.suffix in {".pyc", ".pyo"}:
            continue
        if SKIP_DIRS & set(path.relative_to(PACKAGE).parts):
            continue
        files.append(path.relative_to(PACKAGE))
    return files


def flatten(files: list[Path], out: Path, entrypoint: str) -> None:
    """Copy the package contents to `out`, rewriting package-absolute imports."""
    for rel in files:
        target = out / (entrypoint if str(rel) == APP_MODULE else rel)
        target.parent.mkdir(parents=True, exist_ok=True)
        if rel.suffix == ".py":
            source = (PACKAGE / rel).read_text(encoding="utf-8")
            rewritten = IMPORT_RE.sub(r"from \1 import ", source)
            leftover = [
                line for line in rewritten.splitlines() if "earthquake_dashboard" in line
            ]
            if leftover:
                raise SystemExit(
                    f"{rel}: cannot flatten, package name survives the rewrite:\n  "
                    + "\n  ".join(leftover)
                )
            target.write_text(rewritten, encoding="utf-8")
        else:
            shutil.copy2(PACKAGE / rel, target)


def write_requirements(out: Path) -> list[str]:
    """Emit requirements.txt from the project's runtime dependencies."""
    with PYPROJECT.open("rb") as handle:
        deps = tomllib.load(handle)["project"]["dependencies"]
    body = "\n".join(deps)
    (out / "requirements.txt").write_text(
        "# Generated by scripts/bundle_plotly.py from pyproject.toml.\n"
        "# Edit the dependencies there, not here.\n" + body + "\n",
        encoding="utf-8",
    )
    return deps


def import_check(out: Path, entrypoint: str) -> None:
    """Import the flattened entrypoint the way the platform will."""
    module = entrypoint.removesuffix(".py")
    result = subprocess.run(
        [sys.executable, "-c", f"import {module}"],
        cwd=out,
        capture_output=True,
        text=True,
        # Without this the check leaves __pycache__ behind and the bundle ships it.
        env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
    )
    if result.returncode != 0:
        tail = (result.stderr or result.stdout).strip().splitlines()[-6:]
        raise SystemExit(
            f"bundle fails to import as `{module}`:\n  " + "\n  ".join(tail)
        )


def archive(out: Path) -> Path:
    """Zip the bundle, keeping `out.name` as the enclosing folder."""
    zip_path = out.with_suffix(".zip")
    zip_path.unlink(missing_ok=True)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
        for path in sorted(out.rglob("*")):
            if path.is_file():
                zipf.write(path, Path(out.name) / path.relative_to(out))
    return zip_path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO / "dist" / "earthquake-dashboard-plotly",
        help="bundle directory (default: dist/earthquake-dashboard-plotly, gitignored)",
    )
    parser.add_argument(
        "--entrypoint",
        default=DEFAULT_ENTRYPOINT,
        help=f"name for the app module in the bundle (default: {DEFAULT_ENTRYPOINT}, "
        "the name the live app is frozen to)",
    )
    parser.add_argument("--no-zip", action="store_true", help="skip the .zip")
    parser.add_argument(
        "--no-check",
        action="store_true",
        help="skip importing the flattened entrypoint",
    )
    args = parser.parse_args()

    out = args.out.resolve()
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    entrypoint = args.entrypoint
    if not entrypoint.endswith(".py"):
        entrypoint += ".py"

    files = collect()
    flatten(files, out, entrypoint)
    deps = write_requirements(out)

    if not args.no_check:
        import_check(out, entrypoint)
        print(f"import check: `import {entrypoint.removesuffix('.py')}` OK")

    total = 0
    print(f"\n{out.relative_to(REPO)}/")
    for path in sorted(out.rglob("*")):
        if path.is_file():
            size = path.stat().st_size
            total += size
            print(f"  {path.relative_to(out)!s:<28} {size / 1024:>8.1f} KiB")
    print(f"  {'total':<28} {total / 1024:>8.1f} KiB")

    if total > UI_SIZE_LIMIT:
        print(f"\nWARNING: over the {UI_SIZE_LIMIT // 1024 // 1024} MiB web-UI limit.")

    if not args.no_zip:
        zip_path = archive(out)
        print(f"\nzipped  {zip_path.relative_to(REPO)}  ({zip_path.stat().st_size / 1024:.1f} KiB)")

    print(f"\nEntrypoint: {entrypoint}   Dependencies: {len(deps)} in requirements.txt")
    print("Upload at https://cloud.plotly.com/ -> Publish, and pick Python 3.13.")


if __name__ == "__main__":
    main()
